#!/bin/bash
# This is a basic bash script




i=0
while [ $i -le 10 ]; do
	echo i:$i
	((i+=1))


done


j=0
until [ $j -ge 10 ];do 
	echo i:$j
	((j+=1))

done






























#freespace=$(df -h / | grep -E "\/$" | awk '{print $4}')
#greentext="\033[32m"
#bold="\033[1m"
#normal="\033[0m"
#logdate=$(date + %Y%m%d")
#logfile="$logdate"_report.log
#
#echo -e $bold"Quick system report for "$greentext"$HOSTNAME"$normal
#printf "\tSystem type:\t%s\n" $MACHTYPE
#printf "\tBash Version:\t%s\n" $BASH_VERSION
#printf "\tFree Space:\t%s\n" $freespace
#printf "\tFiles in dir:\t%s\n" $(ls |wc -l)
#printf "\tGenerated on:\t%s\n" $(date +"%m/%d/%y") # US date format
#echo -e $greentext"A summary of this info has been saved to $logfile"$normal
#
#cat <<- EOF > $logfie
#	This report was automatically generated by my bash script
#	it contains a brief summary of some system information.
#EOF
#
#
#
#
#
#
#
#
##a=()
##b=("apple" "banana" "cherry")
##echo ${b[2]}
##b[5]="kiwi"
##b+=mango
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##[[ "cat" == "cat" ]]
##echo $?
#
##[[ "cat" == "dog" ]]
##echo $?
#
##[[ 20 > 100 ]]
##echo $?
#
##[[ 20 < 100 ]]
##echo $?
#
##[[ 20 -gt 100]]
##echo $?
#
#
#
###
###
###
###
###
###
###
###
###
###
###
###
###
###
###
###
###
###
###
##greeting="hello"
##
##echo $greeting, world \(planet\)!
##
##echo '$greeting, world (planet)!'
##
##echo "$greeting, world (planet)!"
#
#
#a=hello
#b="good morning"
#c=16
#
#echo $a
#echo $b
#echo $c
#
#echo $pwd

#echo $HOSTNAME

#echo $SECONDS

